### ISSUE TITLE
The image id '[ami-4296ec3a]' does not exist

### ISSUE THREAD

**Issue by JakeHagen** [grailbio/reflow#126]
Hi When trying to use reflow I get the error
```InvalidAMIID.NotFound: The image id '[ami-4296ec3a]' does not exist```

It looks like its fairly easy to change the ami in the config, but then reflow wants me to run ```reflow migrate```

It also looks easy to change the config validation function to allow different amis, but it make me wonder if I am doing something wrong.

So, are you still using ami-4296ec3a? If so, how? If not, what ami are you using?

Thanks
Jake

**Comment by prasadgopal** [comment]
That is the AMI we use and it works for us. It has probably got to do with AWS region may be? It is available in us-west-2. Or you can move to recent CoreOS AMI available in your region and see if it works for you?

**Comment by JakeHagen** [comment]
Ah I see. you are right. That AMI is only available in us-west-2. I will change to ami-a32d46dc for us-east-1, based on http://stable.release.core-os.net/amd64-usr/1745.5.0/coreos_production_ami_hvm.txt . 

Thank you for your help
