### ISSUE TITLE
Option to maintain local reflowlet if host is running a Docker daemon

### ISSUE THREAD

**Issue by mariusae** [grailbio/reflow#13]
If the local host is running a Docker daemon, reflow should transparently (optionally) maintain a reflowlet on the local host, so that it can participate in the cluster. This will help to avoid allocating cluster resources needlessly for small jobs.

**Comment by brysgo** [comment]
It might get more people playing with the language if there was a single instance, non-cluster implementation.

**Comment by mariusae** [comment]
FWIW, you can already run `reflow` in local mode: `reflow run -local ...` which will use the local Docker daemon. This proposes in effect to automatically use local resources if the job is small enough.

**Comment by brysgo** [comment]
I figured the former part out and deleted my comment :-)

**Comment by mariusae** [comment]
👍 it should be documented more carefully..

**Comment by mariusae** [comment]
I'm not sure this is a good idea.
