### ISSUE TITLE
Reflow 1.5.0 and 1.6.0 releases are missing binaries

### ISSUE THREAD

**Issue by niemasd** [grailbio/reflow#130]
The [1.5.0](https://github.com/grailbio/reflow/releases/tag/reflow1.5.0) and [1.6.0](https://github.com/grailbio/reflow/releases/tag/reflow1.6.0) releases of Reflow are missing binaries, so the ["Getting Reflow"](https://github.com/grailbio/reflow#getting-reflow) instructions in the README are not accurate:

> You can get binaries (macOS/amd64, Linux/amd64) for the latest release at the [GitHub release page](https://github.com/grailbio/reflow/releases).

**Comment by alperyilmaz** [comment]
and `buildreflow` step is not trivial to troubleshoot when it fails for Go language noobs.. Binaries would be greatly appreciated..

**Comment by prb2** [comment]
The [1.5.0 and 1.6.0 releases](https://github.com/grailbio/reflow/releases) have been updated with binaries.

`buildreflow` is currently broken, but I have a fix in the works that will be landed soon.
