### ISSUE TITLE
Building reflow doesn't work on recent versions of Go

### ISSUE THREAD

**Issue by niemasd** [grailbio/reflow#131]
I installed the most recent Go version (1.16.3) from the following URL:

https://golang.org/doc/install

I can confirm that it's working:

```bash
$ go version
go version go1.16.3 linux/amd64
```

However, when I try to build from scratch, I get the following error when I try to install `buildreflow`:

```bash
$ go install github.com/grailbio/reflow/cmd/buildreflow
go: github.com/grailbio/base@v0.0.7-0.20191216215904-c504fd73cad7 requires
        v.io@v0.1.7: parsing go.mod: go.mod:3: invalid go version '1.13.1': must match format 1.23
```

I tried installing Go version 1.16 instead to see if the issue was having a version number `#.#.#` instead of `#.#`, but same issue:

```bash
$ go version
go version go1.16 linux/amd64
$ go install github.com/grailbio/reflow/cmd/buildreflow
go: github.com/grailbio/base@v0.0.7-0.20191216215904-c504fd73cad7 requires
        v.io@v0.1.7: parsing go.mod: go.mod:3: invalid go version '1.13.1': must match format 1.23
```

I Googled it a bit and found the following link, which suggests that I should try Go version 1.13:

https://git.canopsis.net/canopsis/canopsis/-/issues/2698

I installed Go version 1.13, and now it seems to work:

```bash
$ go version
go version go1.13 linux/amd64
$ go install github.com/grailbio/reflow/cmd/buildreflow
go: downloading golang.org/x/tools v0.0.0-20190911174233-4f2ddba30aff
go: extracting golang.org/x/tools v0.0.0-20190911174233-4f2ddba30aff
go: finding golang.org/x/tools v0.0.0-20190911174233-4f2ddba30aff
```

It would be good to either (1) add support for more recent versions of Go, or (2) mention in the build instructions that Reflow requires Go version 1.13

**Comment by prb2** [comment]
Fixed by @prasadgopal in #133.
