### ISSUE TITLE
reflow info fails, rebuild with fix also fails

### ISSUE THREAD

**Issue by elimoss** [grailbio/reflow#141]
reflow info fails with `reflow: taskdb: no provider for type taskdb.TaskDB`

this seems to be similar to the problem encountered in #129, but the fix provided in that thread seems to be absent from the repo and the current release. I'd add it myself and rebuild, but when I try to do this I see

```
../../tool/cost.go:15:2: no required module provides package github.com/grailbio/base/cloud/spotfeed; to add it:
        go get github.com/grailbio/base/cloud/spotfeed
../../blob/s3blob/s3blob.go:21:2: no required module provides package github.com/grailbio/base/s3util; to add it:
        go get github.com/grailbio/base/s3util
```
and attempting to do this gives me
```
go get: module github.com/grailbio/base@upgrade found (v0.0.10), but does not contain package github.com/grailbio/base/cloud/spotfeed
```
and
```
go get: module github.com/grailbio/base@upgrade found (v0.0.10), but does not contain package github.com/grailbio/base/s3util
```

So I'm a bit stuck. I guess I need either a new release binary incorporating the fix from the previous issue (assuming that solves my problem, too) or a solution to my build issue. 

Thanks in advance for any help you can provide!

**Comment by swami-m** [comment]
Sorry for the delay in making this work, but with the [new 1.15.0 release](https://github.com/grailbio/reflow/releases/tag/reflow1.15.0), one can [setup a taskdb if desired](https://github.com/grailbio/reflow#setting-up-a-taskdb).
