### ISSUE TITLE
Reflow evaluator panics when a negative float is used as a parameter

### ISSUE THREAD

**Issue by hyjkim** [grailbio/reflow#18]
Using a negative float as a parameter causes the following error:

```panic while evaluating <float>unop("-", <float>const(0.25): interface conversion: values.T is *big.Float, not *big.Int```

The offending code can be found at https://github.com/grailbio/reflow/blob/master/syntax/eval.go#L868

**Comment by mariusae** [comment]
cc: @prasadgopal
