### ISSUE TITLE
support aws credentials files

### ISSUE THREAD

**Issue by ryanking** [grailbio/reflow#2]
It would be nice if env variables were not required for configuring.

We don't use env variables, but [credentials files](http://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html), which the aws go sdk supports.

**Comment by mariusae** [comment]
Agreed. This should be pretty easy to support.

**Comment by ryanking** [comment]
I would expand to say that reflow should support all aws auth mechanisms - http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by nataren** [comment]
I am starting to work on this.

**Comment by mariusae** [comment]
This is now supported as of 2a90fc5a82053430f40598362ef2ec33d4ccb023.

Reflow will also now use the config in `~/.aws/config` (e.g., to configure which default region to use) when `AWS_SDK_LOAD_CONFIG` is set to a truthy value. (This is the AWS SDK default.)

```
% env | grep ^AWS
% ls /Users/marius/.aws
config		credentials	shell/
% AWS_SDK_LOAD_CONFIG=1 /Users/marius/go/bin/reflow run /Users/marius/hello.rf
reflow: run ID: db0e2c2d
reflow: total n=1 time=0s
	ident      n   ncache transfer runtime(m) cpu mem(GiB) disk(GiB) tmp(GiB)
	hello.Main 1   1      0B                                         
	
file(sha256=sha256:f13a55b71d31ec3df35f99d6b6332b23a4967312314456941aff922a7d354818, size=8)
```
