### ISSUE TITLE
An Example with Many Files would be Superb

### ISSUE THREAD

**Issue by zachcp** [grailbio/reflow#22]
Hi Team Reflow,

I've been looking at your docs and I like what I see.  It seems you've got an execution model that matches the cloud quite well and that you can effectively elide much of the complexity of running batch jobs on AWS. However, I would love  to see some more examples with lots of files. Much of our standard processing is "take these 5000 files from an S3 bucket, do something to them, and put them in a different S3 bucket with a different file extension." As someone coming from a very Make-centric workflow where jobs are defined by filenames, it would be of great help to have a few examples of how to do this within Reflow.

Thanks for making your software available,
zach cp

**Comment by mariusae** [comment]
Hi Zach CP, thanks for your feedback. We're definitely looking at bringing a lot more examples and also some officially supported modules for common tasks and also bioinformatics.

Do you have a particular kind of task you're looking for? If you have a concrete example I'd be happy to provide an example module or at least an outline of one..

**Comment by zachcp** [comment]
Hi @mariusae,


Thank you for your generous offer.  As an example, how would you use Reflow in the following scenario:

1. You've got 100 (or 1000) paired-end fastq files in an S3 bucket. Each one is from a different bacterial genome.

2. You want to pull those genomes to an EC2 image and assemble them.

3. You want to take the assemblies and call SNPs on them.

4. You need to push the assembly file and the SNP output directory back to a different S3 bucket/sub-bucket based on the original input filename.

A sketch of how you would approach this in Reflow would be helpful. Real jobs would potentially be more complicated but if you could sketch out the way you would think about this problem to best match Reflow's execution model, it would be a great start.

thanks,
zach cp

```
# S3 Single Genome Source:
s3://myproject/rawdata/genome01_F.fastq
s3://myproject/rawdata/genome01_R.fastq

# S3 Single Genome Assembly Spades Output:
# note: filename based on input
s3://myproject/assemblies/genome01_assembly.fasta

# S3 Single Genome SNP Calling Output:
# note: file directory based on input
s3://myproject/snps/genome01_snps/

# S3 Reference Genome
# note: reference to be used for each job
s3://myreferencedata/ref.fasta

# pseudo commands for local files
spades -pe1 genome01_F.fastq -pe2 genome01_R.fastq -out  genome01_assembly.fasta
snippy -in genome01_assembly.fasta -ref ref.fasta -outdir

```

**Comment by mariusae** [comment]
Here's a worked example:

    https://gist.github.com/mariusae/24ff59757050076e0263af58edf54e00

**Comment by mariusae** [comment]
@zachcp does the above accomplish what you set out to?

**Comment by zachcp** [comment]
Thank you @mariusae, for your example. I read your code and think it should work. I will try to run it this weekend and can report any issues I find.
