### ISSUE TITLE
no allocs available in pool

### ISSUE THREAD

**Issue by dimenwarper** [grailbio/reflow#23]
Firstly, kudos to the team, the whole reflow concept is illuminating.

I have a bug to report. I just did a fresh reflow install on a debian stretch google cloud machine using go 1.9.4 (downloaded directly from golang.org, not using any debian packages)

Trying to run hello.rf, I get

```
2018/02/21 22:38:15 ec2cluster: launched instance i-0215b500c0da1f09d: t2.small{mem:1.9GiB cpu:1 disk:250.0GiB intel_avx:1}
2018/02/21 22:39:32 ec2cluster: failed to allocate from pool: unavailable: no allocs available in pool; provisioning new instances
```

New instances are spun up but then terminated, never used. 

Previous reflow installs worked just fine (e.g. using 59a09d7e72f1356f50f0d85301afbea1d828a6f9 as HEAD)

**Comment by mariusae** [comment]
Are you building your own binary?

**Comment by dimenwarper** [comment]
Ah, there you go, yes this was building my own binary and yes I forgot to execute releasereflow. Will use the binaries from now on.

May have been my interpretation of the docs, but I read it like running releasereflow was optional, and needed only when you modified the code after building the reflow binary.

**Comment by mariusae** [comment]
FYI [reflow0.6](https://github.com/grailbio/reflow/releases/tag/reflow0.6) was just released, and contains the latest in master.
