### ISSUE TITLE
AWS token expiration

### ISSUE THREAD

**Issue by hchauvin** [grailbio/reflow#29]
The results of a long-running job could not be uploaded because the session expired.  Version: HEAD, go 1.10.  Relevant output:
```
...
reflow: retrying error cache.Transfer: unavailable:
transfer sha256:f11f589ae07a7498d87e83885e11de64cf489a3edeb309da5662cea82944d1b4: ExpiredToken: The provided token has expired.
status code: 400, request id: XXX, host id: XXX
too many tries:
```

Authentication proceeds with EC2 roles in my case.

Any idea?

**Comment by hchauvin** [comment]
Ok now I understand, I had an intuition that is not followed by the code.

Basically, I didn't set the "aws" key of the reflow config, so it defaulted to "awsenv", that is, if no "awsenv" key if specified, to using AWS session.NewSession().  NewSession() looks, among other things, at the following to get its credentials, in this order:
1) Environment variables AWS_*
2) Config at ~/.aws/config.yaml
3) EC2 metadata

I did not specify any environment variable nor any .aws/config.yaml.  However, I launched reflow from an EC2 instance, so NewSession() looked at the EC2 metadata.  I did not think much about it because this is what I expect from launching tools that dials the AWS API.

Now, the problem is that, when the host configuration is marshalled to get to the reflowlet agents, the awsenv key is populated by the then-valid credentials for the host.  But those credentials having been retrieved from the EC2 metadata, they expire after a few hours.  My intuition was not that those credentials carried over in such a manner.

I think this is a naming problem: awsenvconfig does not look at environment variables only.  It uses AWS session.NewSession() which looks at defaults in various places, including EC2 metadata.  I think I can produce a PR that errors when awsenvconfig is used and NewSession() uses an EC2 metadata provider, because this definitely comes back to bit.

**Comment by mariusae** [comment]
Thanks for the sleuthing! Yes, that's indeed an issue here. You probably saw that there is an explicit provider for this, too, called `ec2metadata`. I'll take a look at your change, thanks!

**Comment by mariusae** [comment]
Fwiw, I'd like to eventually change the way credentials are propagated in Reflow, so that the evaluator is responsible for setting and refreshing credentials rather than it being done at boot time. This would allow for ephemeral credentials that are refreshable only locally, as is the case of the EC2 metadata credentials.

**Comment by hchauvin** [comment]
Thank you for the merge, I think I can close this now!
