### ISSUE TITLE
Inconsistent behavior with flag default values set to another flag

### ISSUE THREAD

**Issue by josh-newman** [grailbio/reflow#34]
In this reflow program, reflow fails with an error because `b` depends on `a`:
```lang=text
param (
	a string
	b string = a
)

val Main = b
```
```lang=text
/tmp $ reflow0.6.2 run flags2.rf 
a is undefined; flag parameters may not depend on other flag parameters
/tmp $ reflow0.6.2 run flags2.rf -a "A"
a is undefined; flag parameters may not depend on other flag parameters
/tmp $ reflow0.6.2 run flags2.rf -a "A" -b "B"
a is undefined; flag parameters may not depend on other flag parameters
```

However, if `a` has a default value, behavior changes:
```lang=text
param (
	a string = "default"
	b string = a
)

val Main = b
```
```lang=text
/tmp $ reflow0.6.2 run flags.rf 
"default"
/tmp $ reflow0.6.2 run flags.rf -a "A"
"default"
/tmp $ reflow0.6.2 run flags.rf -a "A" -b "B"
"B"
```

It seems like reflow's behavior in this case is roughly consistent with Go's flag handling. However, I think reflow should handle this differently. In reflow, values are immutable, so it would be surprising to a reflow user for `a` and `b` to have different values after seeing `b = a` (and not setting `b` with a flag).

I would prefer that reflow actually allow `b` to adopt `a`'s effective value (whether that comes from `a`'s default value or an explicit setting of `a`). Alternatively, I think reflow should at least fail in the second case with the "flag parameters may not depend on other flag parameters" error.

**Comment by mariusae** [comment]
I agree this behavior is unintuitive, and we should change it.

**Comment by josh-newman** [comment]
@demetrin, this issue is now fixed, right?

**Comment by demetrin** [comment]
Yes this is fixed. This was actually my first project when I joined GRAIL :)
