### ISSUE TITLE
'interface conversion' panic on 'reflow runbatch'

### ISSUE THREAD

**Issue by batson** [grailbio/reflow#68]
I'm new to `reflow` and quite excited to start using it!

After designing my first job (modeled after @olgabot's https://github.com/czbiohub/kmer-hashing work), I wasn't able to get off the ground.

Are there parameters I need to set somewhere other than the local config file?

Thanks for the help.

```
compute git:(skeeters) ✗ reflow runbatch                    
panic: interface conversion: interface {} is nil, not map[interface {}]interface {}

goroutine 1 [running]:
main.validateConfig(0x1d00f80, 0xc420498000, 0x1d01160, 0xc420466c00)
	/Users/josh/go/src/github.com/grailbio/reflow/cmd/reflow/migrate.go:91 +0x198
github.com/grailbio/reflow/tool.(*Cmd).Main(0xc420476360)
	/Users/josh/go/src/github.com/grailbio/reflow/tool/main.go:274 +0x7f5
main.main()
	/Users/josh/go/src/github.com/grailbio/reflow/cmd/reflow/main.go:64 +0x411
```

**Comment by batson** [comment]
The line it's failing on is 

`ec2keys := cfg.Value("ec2cluster").(map[interface{}]interface{})` in `migrate.go`.

Is there some place I am supposed to give it access to my `aws` information?

**Comment by batson** [comment]
In fact, this failure occurs even for `reflow config` or `reflow setup-ec2`.

**Comment by mariusae** [comment]
Ah, apologies. This was an issue that was fixed after the previous release. Let me make a new release for you.

**Comment by batson** [comment]
the new one works for me, thanks so much!
