### ISSUE TITLE
In execs, nested quotes behave differently depending on line breaks 

### ISSUE THREAD

**Issue by cyrusmaher** [grailbio/reflow#78]
The command below does not work if I put the single quotes on the same line:
```
awk -F"\t" '{\
    print "test"\
}' {{to_parse}} 
```

Here is the error message if I remove the line breaks:
```
[script]:12:30: literal not terminated
[script]:12:30: illegal char literal
[script]:13:3: literal not terminated
[script]:14:1: syntax error: unexpected tokExpr, expecting ';'
```

**Comment by mariusae** [comment]
Reflow treats the bytes between `{"` and `"}` as a literal value passed to `bash -c`;
so the problem is with bash, not Reflow.
